### ISSUE TITLE
Not related to project

### ISSUE THREAD

**Issue by RBasiev** [vanilla-thunder/chrome-tab2desktop#1]
Марат, напиши мне пожалуйста на rus.basiev@gmail.com. Меня попросили тебе очень важную новость сообщить. Других контактов не нашел. @vanilla-thunder

**Comment by vanilla-thunder** [comment]
@RBasiev спасибо, я уже все знаю.

**Comment by RBasiev** [comment]
у меня есть контакты Ларисы, если тебе это нужно - напишешь мне на почту. попросили передать
